# server
server:
  port: 8082
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512KB

spring:
  application:
    name: promotion-server
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 20MB # 업로드되는 단일 파일 최대 크기
      max-request-size: 50MB # 하나의 요청에서 허용되는 전체 파일 크기

  cloud:
    aws:
      credentials:
        access-key: dummy
        secret-key: dummy
      region:
        static: ap-northeast-2
      s3:
        bucket: dummy

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        create_empty_composites:
          enabled: true
    show-sql: true
    open-in-view: false

# swagger
springdoc:
  swagger-ui:
    enabled: true
    default-models-expand-depth: 1
    default-model-expand-depth: 5
  use-fqn: true
  override-with-generic-response: false
  



## actuator
management:
  server:
    ### 스캐닝 회피용
    port: 8088
  endpoints:
    enabled-by-default: false
    web:
      base-path: /checker
      exposure:
        include: health,metrics,threads,prometheus

  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true

### dummy
security:
  jwt:
    token: T0V3jKX1f7iP9Sb8H4rV8XxY7A3Z6jT9N5p2R1sLm8Wb5F7P

# Resend email configuration
resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL:noreply@yourdomain.com}

client-url: http://localhost:3000
server-url: https://dev-api.hryedam.co.kr



app:
