server:
  tomcat:
    connection-timeout: 60000
    threads:
      max: 200
    keep-alive-timeout: 30s
    basedir: /home/mardi
    accesslog:
      enabled: true
      directory: ${server.tomcat.basedir}/logs/
      file-date-format: .yyyy-MM-dd
      pattern: '%t %a %A %S %{User-Agent}i %r %b %s %I %D'
      rotate: true
      rename-on-rotate: true
      max-days: 30
      buffered: true

logging:
  file:
    path: ${server.tomcat.basedir}/logs/
  level:
    org:
    springframework: INFO
  logback:
    rolling policy:
      max-history: 10

client-url: https://dev-app.mardi-erp.com/

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

    hikari:
      maximum-pool-size: 25

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

app:
  cors:
    allow-origins:
      - http://localhost:3000
      - http://localhost:3001
      - https://dev-app.mardi-erp.com
      - https://dev-api.mardi-erp.com

  cafe24:
    mall-id: yourmallid
    client-id: yourclientid
    client-secret: yourclientsecret
    redirect-uri: https://yourapp.com/oauth/callback

application:
  env: dev




